import { HistoricalEvent } from "./Components/MapsApp";

const eventsData: HistoricalEvent[] = [
  {
    id: 1,
    title: "Bahrain National Museum",
    description: "The largest and one of the oldest public museums in Bahrain.",
    position: [26.2408014, 50.598086],
    category: "History",
  },
  {
    id: 2,
    title: "Qal'at al-Bahrain (Bahrain Fort)",
    description: "An archaeological site and the former capital of the Dilmun civilization.",
    position: [26.2330953, 50.5198657],
    category: "History",
  },
  {
    id: 3,
    title: "Al Fateh Grand Mosque",
    description: "One of the largest mosques in the world, capable of accommodating over 7,000 worshippers.",
    position: [26.2189298, 50.5980332],
    category: "Religion",
  },
  {
    id: 4,
    title: "Bab Al Bahrain",
    description: "A historical building located at the entrance of the Manama Souq.",
    position: [26.2344, 50.5755],
    category: "History",
  },
  {
    id: 5,
    title: "Bahrain International Circuit",
    description: "A motorsport venue and the home of the Bahrain Grand Prix.",
    position: [26.0325, 50.5107],
    category: "Sports",
  },
  {
    id: 6,
    title: "Tree of Life",
    description: "A 400-year-old tree standing in the desert, a natural wonder of Bahrain.",
    position: [25.9965, 50.5832],
    category: "Nature",
  },
  {
    id: 7,
    title: "Bahrain World Trade Center",
    description: "A twin-tower complex featuring three wind turbines integrated into its design.",
    position: [26.2314, 50.5805],
    category: "Modern Architecture",
  },
  {
    id: 8,
    title: "Beit Al Quran",
    description: "An Islamic museum that houses one of the world's most valuable collections of Quranic manuscripts.",
    position: [26.2297, 50.5895],
    category: "Religion",
  },
  {
    id: 9,
    title: "The Avenues Bahrain",
    description: "A waterfront shopping mall offering a variety of shops, restaurants, and entertainment.",
    position: [26.2420, 50.5777],
    category: "Shopping",
  },
  {
    id: 10,
    title: "Amwaj Islands",
    description: "A group of man-made islands with luxury homes, hotels, and recreational facilities.",
    position: [26.2855, 50.6629],
    category: "Recreation",
  },
  {
    id: 11,
    title: "Riffa Fort",
    description: "A historic fort offering views over the Riffa Valley and insight into Bahrain's past.",
    position: [26.1228, 50.5650],
    category: "History",
  },
  {
    id: 12,
    title: "Muharraq Souq",
    description: "A traditional market offering a wide range of goods from spices to traditional sweets.",
    position: [26.2612, 50.6110],
    category: "Shopping",
  },
  {
    id: 13,
    title: "Dilmun Burial Mounds",
    description: "Ancient burial mounds dating back to the Dilmun civilization.",
    position: [26.1327, 50.5532],
    category: "History",
  },
  {
    id: 14,
    title: "Royal Camel Farm",
    description: "A farm housing hundreds of camels, offering visitors an up-close experience.",
    position: [26.1452, 50.4889],
    category: "Nature",
  },
  {
    id: 15,
    title: "Seef Mall",
    description: "One of Bahrain's most popular shopping malls, with a range of shops, dining options, and a cinema.",
    position: [26.2337, 50.5422],
    category: "Shopping",
  },
  {
    id: 16,
    title: "Arad Fort",
    description: "A 15th-century fort in Muharraq that played a crucial role in the country's defense.",
    position: [26.2572, 50.6204],
    category: "History",
  },
  {
    id: 17,
    title: "Al Areen Wildlife Park",
    description: "A nature reserve and zoo home to over 100,000 plants and trees, and more than 500 animals.",
    position: [26.0372, 50.5151],
    category: "Nature",
  },
  {
    id: 18,
    title: "Bahrain City Centre",
    description: "A large shopping mall with international brands, a cinema, and an indoor water park.",
    position: [26.2241, 50.5470],
    category: "Shopping",
  },
  {
    id: 19,
    title: "Saar Archaeological Site",
    description: "An archaeological site that dates back to the Dilmun period, showcasing ancient settlement ruins.",
    position: [26.1994, 50.4979],
    category: "History",
  },
  {
    id: 20,
    title: "Shaikh Isa Bin Ali House",
    description: "A traditional Bahraini house in Muharraq, offering a glimpse into 19th-century life.",
    position: [26.2586, 50.6125],
    category: "History",
  },
  {
    id: 21,
    title: "Al Dar Islands",
    description: "A group of small islands offering beaches, water sports, and a relaxing getaway.",
    position: [26.1928, 50.6671],
    category: "Recreation",
  },
  {
    id: 22,
    title: "Lost Paradise of Dilmun Water Park",
    description: "A large water park themed around the ancient Dilmun civilization.",
    position: [26.0322, 50.5105],
    category: "Recreation",
  },
  {
    id: 23,
    title: "Bahrain Financial Harbour",
    description: "A waterfront commercial development that is a symbol of modern Bahrain.",
    position: [26.2435, 50.5725],
    category: "Modern Architecture",
  },
  {
    id: 24,
    title: "Al Jasra House",
    description: "The birthplace of Bahrain's former ruler, showcasing traditional Bahraini architecture.",
    position: [26.1693, 50.4557],
    category: "History",
  },
  {
    id: 25,
    title: "Sitra Park",
    description: "A popular park with gardens, walking paths, and playgrounds, offering views of the sea.",
    position: [26.1553, 50.6079],
    category: "Recreation",
  },
  {
    id: 26,
    title: "Wahooo! Waterpark",
    description: "An indoor-outdoor water park located in Bahrain City Centre, ideal for family fun.",
    position: [26.2241, 50.5470],
    category: "Recreation",
  },
  {
    id: 27,
    title: "Shajarat Al-Hayat",
    description: "A 400-year-old tree in the middle of the desert, known as the Tree of Life.",
    position: [25.9965, 50.5832],
    category: "Nature",
  },
  {
    id: 28,
    title: "Bu Maher Fort",
    description: "A fort in Muharraq, important for understanding Bahrain's maritime history.",
    position: [26.2413238, 50.6135954],
    category: "History",
  },
  {
    id: 29,
    title: "Ras Sanad Mangrove Forest",
    description: "A mangrove forest providing a unique ecosystem and home to various bird species.",
    position: [26.1803, 50.5962],
    category: "Nature",
  },
  {
    id: 30,
    title: "King Fahd Causeway",
    description: "A series of bridges and causeways connecting Bahrain and Saudi Arabia, offering stunning views.",
    position: [26.1488, 50.3083],
    category: "Modern Architecture",
  } 
];

export default eventsData;
